### ISSUE TITLE
lua error sod

### ISSUE THREAD

**Issue by Typhosy** [caboyd/LibHealComm-4.0#14]
43x LibHealComm-4.0-113/LibHealComm-4.0.lua:887: attempt to get length of local 'average' (a nil value)
[string "@LibHealComm-4.0-113/LibHealComm-4.0.lua"]:887: in function <LibHealComm-4.0/LibHealComm-4.0.lua:875>
[string "@LibHealComm-4.0-113/LibHealComm-4.0.lua"]:1182: in function <LibHealComm-4.0/LibHealComm-4.0.lua:1180>
[string "=(tail call)"]: ?
[string "@LibHealComm-4.0-113/LibHealComm-4.0.lua"]:3063: in function `?'
[string "@LibHealComm-4.0-113/LibHealComm-4.0.lua"]:3577: in function <LibHealComm-4.0/LibHealComm-4.0.lua:3573>

Locals:
spellData = <table> {
 levels = <table> {
 }
 averages = <table> {
 }
 coeff = 0.357000
}
spellName = "Nourish"
spellID = 408247
spellRank = nil
average = nil
requiresLevel = 1
(*temporary) = <function> defined =[C]:-1
(*temporary) = 35
(*temporary) = nil
(*temporary) = "attempt to get length of local 'average' (a nil value)"
type = <function> defined =[C]:-1
isSoD = true
min = <function> defined =[C]:-1
playerLevel = 35

**Comment by caboyd** [comment]
finally fixed in https://github.com/caboyd/LibHealComm-4.0/releases/tag/SODv15
